{ pkgs ? import <nixpkgs> {} }:

let
  # Our macro-enhanced patches
  introspection-patch = pkgs.writeText "add-introspection.patch" ''
    diff --git a/compiler/rustc_driver/src/lib.rs b/compiler/rustc_driver/src/lib.rs
    index 1234567..abcdefg 100644
    --- a/compiler/rustc_driver/src/lib.rs
    +++ b/compiler/rustc_driver/src/lib.rs
    @@ -100,6 +100,10 @@ pub fn main() {
         let start_time = Instant::now();
         let exit_code = catch_with_exit_code(|| {
             let args = env::args_os().collect::<Vec<_>>();
    +        
    +        // Macro introspection hook added by patch-build-rs
    +        eprintln!("🔍 Rustc invoked with macro introspection enabled");
    +        
             RunCompiler::new(&args, &mut DefaultCallbacks).run()
         });
         let end_time = Instant::now();
  '';

in pkgs.rustc.overrideAttrs (old: {
  pname = "rustc-with-macros";
  patches = (old.patches or []) ++ [ introspection-patch ];
  
  postInstall = old.postInstall or "" + ''
    echo "🦀 Macro-enhanced Rust compiler installed"
    echo "Generated by patch-build-rs automorphic system"
  '';
})
