//! This file is automatically generated by the `autoheader!` macro.
//! Do not modify directly.

#[proc_macro]
pub fn autoheader(_input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    // For now, this macro does nothing.
    // Its purpose is to act as a marker for auto-generated headers.
    proc_macro::TokenStream::new()
}