use std::env;
use std::fs::{self, File};
use std::io::Write;
use std::path::PathBuf;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let out_dir = PathBuf::from(env::var("OUT_DIR")?);
    let dest_path = out_dir.join("generated_lib.rs"); // Write to OUT_DIR as a distinct file

    let mut file = File::create(&dest_path)?;

    writeln!(file, "// File generated by build.rs")?;
    writeln!(file, "// Re-exports components of this crate.")?;
    writeln!(file)?;

    // List all files in src/ and generate pub use statements for them
    let src_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR")?).join("src");
    for entry in fs::read_dir(src_dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_file() && path.extension().map_or(false, |ext| ext == "rs") {
            let file_stem = path.file_stem().expect("File should have a stem").to_string_lossy();
            if file_stem != "lib" && file_stem != "generated_lib" { // Don't re-export lib.rs or the generated file itself
                writeln!(file, "pub mod {};", file_stem)?; // Declare the module
                writeln!(file, "pub use self::{}::*;", file_stem)?; // Re-export its contents
                writeln!(file)?;
            }
        }
    }

    // Tell cargo to re-run this build script if src/ changes
    println!("cargo:rerun-if-changed=src/");

    Ok(())
}
